org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=false
kotlin.incremental=false
skipDependencyChecks=true
android.overrideVersionCheck=true
systemProp.user.home=C:/Users/saswa
